// Tese metodológica do índice MARÉ · gerada dos dados e do código vivos (27/08/2026)
const fs = require('fs');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, ImageRun, PageBreak, Table, TableRow, TableCell, WidthType, BorderStyle, ShadingType } = require('docx');

const INK = '2B2118', MUT = '524737', TERRA = 'A65F3F', AZUL = '35566B';

// trecho VERBATIM do motor (autenticidade sobre elegância)
const codigo = fs.readFileSync('recalcular_mare.py', 'utf-8');
let ini = codigo.indexOf('def calcular');
if (ini < 0) ini = codigo.indexOf('def ');
const trecho = codigo.slice(ini).split('\n').slice(0, 22).join('\n');

const P = (t, opts = {}) => new Paragraph({
  alignment: AlignmentType.JUSTIFIED, spacing: { after: 160, line: 312 },
  children: [new TextRun({ text: t, size: 22, font: 'Georgia', color: INK, ...opts.run })], ...opts.par });
const H1 = t => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 200 },
  children: [new TextRun({ text: t, size: 30, bold: true, font: 'Georgia', color: INK })] });
const H2 = t => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 140 },
  children: [new TextRun({ text: t, size: 25, bold: true, font: 'Georgia', color: AZUL })] });
const EQ = t => new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 120, after: 160 },
  children: [new TextRun({ text: t, size: 22, italics: true, font: 'Cambria', color: INK })] });
const FIG = (arq, legenda, largura, altura) => [
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 160, after: 60 },
    children: [new ImageRun({ type: 'png', data: fs.readFileSync(arq), transformation: { width: largura, height: altura } })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 220 },
    children: [new TextRun({ text: legenda, size: 18, italics: true, font: 'Georgia', color: MUT })] })];
const CODE = t => t.split('\n').map(l => new Paragraph({ spacing: { after: 0, line: 240 },
  shading: { type: ShadingType.CLEAR, fill: 'F5F1E8' },
  children: [new TextRun({ text: l.length ? l : ' ', size: 16, font: 'Consolas', color: INK })] }));
const REF = t => new Paragraph({ alignment: AlignmentType.LEFT, spacing: { after: 120 }, indent: { left: 340, hanging: 340 },
  children: [new TextRun({ text: t, size: 20, font: 'Georgia', color: INK })] });

const filhos = [
  // ---- capa ----
  new Paragraph({ spacing: { before: 2400 } }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'MEDINDO A PREPARAÇÃO DEMONSTRÁVEL', size: 40, bold: true, font: 'Georgia', color: INK })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 160 }, children: [new TextRun({ text: 'Construção, metodologia e fundamentos do índice MARÉ para o ciclo El Niño 2026/2027 no Brasil', size: 26, font: 'Georgia', color: MUT })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 480 }, children: [new TextRun({ text: 'Observatório El Niño 2026/2027 · Futura Evidence Lab', size: 22, font: 'Georgia', color: TERRA })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 120 }, children: [new TextRun({ text: 'MARÉ v2.2.3 · monitorelnino.com.br · agosto de 2026', size: 20, font: 'Georgia', color: MUT })] }),
  new Paragraph({ children: [new PageBreak()] }),

  // ---- resumo ----
  H1('Resumo'),
  P('Este documento apresenta, em formato acadêmico, a construção do MARÉ (Medida de Antecipação e Resposta ao El Niño), índice composto que mede a preparação demonstrável publicamente de estados e municípios brasileiros ante o ciclo El Niño 2026/2027. Buscas dirigidas não localizaram precedente de índice específico de preparação para eventos ENSO, em qualquer acepção do termo, o que situa o exercício em terreno pouco coberto pela literatura, sobretudo a lusófona. O índice combina três componentes equiponderados (instrumento estadual, população coberta por instrumentos municipais e antecipação frente ao primeiro boletim oficial do Painel El Niño federal), agregados com elemento geométrico e piso, e quantifica incerteza por simulação de Monte Carlo com dez mil sorteios de pesos. O desenho segue as boas práticas do manual OCDE/JRC de indicadores compostos e dialoga com os análogos nacionais e latino-americanos (ICM da SEDEC, IGR do BID-IDEA), diferenciando-se deles pela avaliação documental externa, em vez de auto-relato, e pela exclusão fundamentada dos atos de resposta. Na fotografia de 26/08/2026, a média nacional é 41,1 em 100, com o Paraná na liderança e sete estados sem instrumento estadual localizado. A discussão examina os fundamentos teóricos das principais decisões: por que o índice mede arcabouço público e não capacidade instalada; por que decretos de emergência recebem crédito zero; como fenômenos de instalação lenta exigiram a ampliação do critério antecipatório para limiares observacionais; e por que o financiamento preventivo, revelado pelo caso Prepara RS, é reconhecido editorialmente mas ainda não pontuado. O texto é dirigido igualmente a leitores acadêmicos, jornalistas e formuladores de políticas.'),
  P('Palavras-chave: El Niño; preparação para desastres; indicadores compostos; defesa civil; transparência pública; Brasil.', { run: { italics: true, color: MUT } }),
  H1('Sumário executivo para leitores com pressa'),
  P('O que é. Um índice de 0 a 100 que mede, para cada estado brasileiro, quanto da preparação para o El Niño 2026/2027 está demonstrado em documento público verificável: plano estadual, planos municipais ponderados pela população que cobrem, e antecipação frente ao primeiro alerta federal.'),
  P('O que diz a fotografia de agosto de 2026. Média nacional de 41,1 (faixa em construção); Paraná na liderança; sete estados sem instrumento estadual localizado; quinze dos vinte instrumentos estaduais atacando o grupo de riscos da seca, que é o risco projetado para Norte e Nordeste; 254 municípios verificados um a um.'),
  P('O que o índice não diz. Não mede capacidade real instalada, suficiência de recursos nem qualidade de execução. Nota alta é condição necessária, não garantia; nota baixa é evidência forte de arcabouço ausente. Ausência de registro não prova ausência de preparação: prova que o público não consegue encontrá-la.'),
  P('As três regras que explicam a maioria das notas. Decretos de emergência não pontuam (são resposta a dano, e a evidência brasileira mostra que respondem também à política); cobertura declarada sem documento vale metade (declarar não é provar); e atos antecipatórios disparados por previsão ou por limiar público de índice oficial recebem crédito (antecipar-se pontua, remediar não).'),
  P('A descoberta institucional do ciclo. O Rio Grande do Sul criou a primeira transferência preventiva em massa localizada no país: dinheiro antes do dano, condicionado a plano de contingência. O índice a reconhece editorialmente e explica por que ainda não a pontua; e registra, por comparação internacional, os cinco desenhos que permitiriam ao Brasil inteiro agir mais rápido.'),
  new Paragraph({ children: [new PageBreak()] }),

  // ---- 1 introdução ----
  H1('1. Introdução'),
  P('Em 29 de junho de 2026, o Painel El Niño federal (INPE, INMET, ANA, Cemaden, SGB e SEDEC) publicou seu primeiro boletim para o ciclo 2026/2027, projetando seca na Amazônia e no semiárido e chuvas extremas no Sul e Sudeste. A pergunta que motivou este trabalho é simples de enunciar e difícil de responder com rigor: diante de um risco anunciado com meses de antecedência, quanto da preparação dos governos brasileiros é demonstrável publicamente? A ênfase no advérbio é o coração do método. Não se mede aqui a capacidade real instalada, que exigiria inspeção, exercício simulado e auditoria de recursos; mede-se a existência, a natureza, o alcance populacional e a antecipação dos instrumentos formais que qualquer cidadão pode localizar, ler e cobrar.'),
  P('Três razões justificam esse recorte, desenvolvidas na seção 6. Primeiro, uma razão filosófica: capacidade é propriedade disposicional, no sentido de Cartwright (1989), que só se manifesta plenamente no evento; medi-la antes exige aproximações que os próprios quadros internacionais, como o IHR-MEF da OMS, resolvem com instrumentos caros e intrusivos. Segundo, uma razão epistemológica: os sistemas que medem preparação por auto-relato, do Sendai Framework Monitor ao ICM brasileiro, carregam vieses documentados; a avaliação documental externa é a correção disponível a um monitor independente. Terceiro, uma razão cívica: o que está publicado é o que a sociedade consegue verificar e exigir, e um índice que sobe a cada plano preventivo publicado converte transparência em incentivo.'),
  P('O ciclo escolhido não é arbitrário. O El Niño 2026/2027 chega três anos após os desastres de 2023 e 2024 no Sul, com memória institucional fresca, boletim federal antecipado e, como este trabalho documenta, o primeiro programa estadual de transferência preventiva em massa localizado no país. É um laboratório natural para observar se o Estado brasileiro consegue se antecipar, e onde.'),
  P('As contribuições são quatro: o próprio índice, com metodologia integralmente pública e reprodutível; um banco de 254 registros municipais e 27 avaliações estaduais verificados em fonte primária; um conjunto de refinamentos conceituais (o teste do objeto para atos antecipatórios, sua extensão a limiares observacionais para fenômenos de instalação lenta, o protocolo declarado versus documentado); e um registro comparado de desenhos institucionais que outros arranjos nacionais adotaram para agir mais rápido, oferecido como elemento para o debate público, sem advocacy.'),

  // ---- 2 fundamentação ----
  H1('2. Fundamentação teórica e trabalhos relacionados'),
  H2('2.1 Indicadores compostos'),
  P('O desenho segue o Handbook on Constructing Composite Indicators (Nardo et al., OCDE/JRC) e a revisão de Greco et al. (2019): pesos declarados como escolha normativa, agregação sensível à compensabilidade e análise de incerteza obrigatória. A revisão de Beccari (2016), cobrindo 106 metodologias de índices de risco e resiliência, mostra que a equiponderação é o padrão dominante da área; o MARÉ a adota com a declaração explícita de que pesos iguais são uma decisão, não uma neutralidade. A agregação inclui elemento geométrico com piso, na linha da média geométrica penalizada e do precedente do fator multiplicativo de Carreño, Cardona e Barbat (2007), reduzindo a compensabilidade perfeita da média aritmética: nota alta em um componente não compensa integralmente a ausência de outro.'),
  H2('2.2 A crítica ao auto-relato'),
  P('A Meta E do Sendai Framework Monitor, cuja escala ordinal informa parte do vocabulário da área, é auto-avaliada pelos próprios Estados; o GAR2019 da UNDRR admite a subjetividade dos escores e que eles medem alinhamento, não implementação. Van Niekerk, Coetzee e Nemakonde (2020) mostram, por triangulação, que a adoção reportada superestima a redução de risco funcional; Chmutina et al. (2021) questionam a validade de constructo do monitoramento centrado em eventos. O ICM da SEDEC, análogo brasileiro direto com vinte variáveis binárias em três dimensões, herda a limitação: é preenchido pelo agente municipal. O MARÉ responde a essa literatura com sua decisão mais estrutural: toda pontuação nasce de avaliação documental externa, com fonte primária citada registro a registro, e o auto-relato, quando usado (coberturas declaradas a tribunais de contas e sistemas estaduais), recebe desconto explícito de cinquenta por cento.'),
  H2('2.3 A economia política das declarações'),
  P('A exclusão dos atos de resposta apoia-se em dois pilares. O conceitual: a terminologia UNDRR distingue preparedness (ex-ante) de response (ações imediatamente antes, durante ou após o desastre), e os índices internacionais de referência (INFORM, WorldRiskIndex, ND-GAIN) medem capacidade e prontidão, nunca decretos. O empírico: para o Brasil, Silva e Batista (2020) demonstram, com dados de 2010 a 2015, que reconhecimentos federais de emergência respondem a alinhamento partidário e calendário eleitoral, contaminando qualquer indicador que os pontue; a engenharia da norma vigente (Portaria MDR 260/2022, verificada em fonte primária) confirma que a rota federal exige dano materializado e fotografado. Um decreto de emergência é, portanto, sinal endógeno à política e posterior ao dano: crédito zero.'),
  H2('2.4 Precedentes subnacionais e lacuna lusófona'),
  P('O IGR do programa BID-IDEA (Cardona, 2005) é o precedente latino-americano de índice de gestão de risco com escalas ordinais de especialista em nível subnacional. A literatura lusófona com scoring quantitativo de planos de contingência é escassa, com a tese de Pinheiro (2016) como exceção relevante, o que aumenta o ônus de documentação transparente assumido por este trabalho.'),

  H2('2.5 Preparação, resposta e o problema da capacidade'),
  P('Duas distinções conceituais sustentam o edifício. A primeira é a fronteira UNDRR entre preparedness, o conhecimento e as capacidades desenvolvidos ANTES para antecipar, responder e recuperar, e response, as ações tomadas imediatamente antes, durante ou após o desastre. O MARÉ é estritamente um índice do primeiro domínio, e cada regra de exclusão deriva dessa escolha. A segunda é a natureza disposicional da capacidade: seguindo Cartwright (1989), capacidade é aquilo que um sistema faria sob ativação, propriedade que nenhum documento garante e que só o evento, ou sua simulação custosa, revela. O quadro de referência internacional que leva essa distinção a sério é o IHR-MEF da Organização Mundial da Saúde, que combina auto-avaliação anual (SPAR), avaliação externa conjunta (JEE), exercícios simulados (SimEx) e revisões pós-ação (AAR): quatro instrumentos, três deles caros e intrusivos, exatamente porque papel não basta. Um monitor jornalístico independente não dispõe desses instrumentos; dispõe do documento público. A honestidade metodológica está em dizer isso na primeira página, com a assimetria probatória como corolário: a ausência de documento é mensurável à distância, a presença de prontidão não.'),
  P('Dessa moldura decorre também a relação declarada com o principal indicador oficial brasileiro, o ICM da SEDEC. Os dois medem objetos irmãos com métodos opostos: o ICM cobre vinte variáveis de capacidade institucional por auto-relato voluntário do agente municipal; o MARÉ cobre um recorte menor (o arcabouço específico do ciclo El Niño) por verificação documental externa. O anexo de harmonização conceitual entre os dois permanece na agenda da versão 2.3, e a comparação mecânica de notas é explicitamente desaconselhada.'),

  // ---- 3 dados ----
  H1('3. Dados, fontes e verificação'),
  H2('3.1 O processo em quatro fases'),
  P('A construção do banco seguiu quatro fases documentadas. A fase um estabeleceu a moldura: definição do objeto, do vocabulário e das fontes admissíveis. A fase dois executou a verificação estadual: para cada uma das 27 unidades federativas, busca dirigida por instrumento específico do ciclo, leitura do documento localizado e julgamento registrado com fonte, ou registro da bateria de buscas negativas. A fase três desceu ao nível municipal: as 27 capitais verificadas individualmente, e a expansão para municípios do interior guiada por três vetores (listas nominais estaduais onde existem, varredura de diários oficiais pela API do Querido Diário e contribuições públicas). A fase quatro é contínua: atualização semanal automatizada, com reavaliação dos registros existentes e incorporação de novos, sob os portões descritos na seção 4.3.'),
  H2('3.2 Vocabulário de categorias e canais'),
  P('Cada registro municipal recebe uma de sete categorias, em ordem decrescente de crédito: plano preventivo específico do ciclo; plano em elaboração com evidência pública; cobertura por instrumento estadual que nomeia o município; plano de ciclo anterior sem atualização; decreto de resposta (registrado para transparência, crédito zero); ato não relacionado ao El Niño; e não localizado após busca registrada. A cada registro associa-se também a espécie jurídica (decreto, portaria, plano, lei) e o canal de obtenção, num vocabulário controlado com validação bloqueante: site oficial do ente, diário oficial, órgão estadual, sistema de controle, imprensa com confirmação primária. A regra de ouro dos canais: imprensa nunca é fonte final, apenas pista; todo registro pontuável exige o documento ou a página oficial que o publica.'),
  H2('3.3 Protocolos de integridade probatória'),
  P('Três protocolos formam a espinha probatória. O protocolo declarado versus documentado: apenas três estados mantêm levantamento público e nominal da existência de planos municipais (Paraná, Santa Catarina e Rio Grande do Sul, via SISDC-PR, Farol do TCE-SC e TCE-RS); coberturas declaradas nesses sistemas, sem documento localizado por esta verificação, entram com metade do crédito da categoria correspondente, operacionalizando a máxima de que declarar não é provar, e o vão entre as duas medidas é publicado como figura própria do site. A bateria negativa: nenhum estado recebe nota mínima sem que as buscas que não o localizaram estejam registradas em log público com gabaritos padronizados por unidade federativa, distinguindo ausência verificada de ausência de verificação; o mesmo desenho foi replicado, nesta versão, para o financiamento preventivo, com vocabulário de três estados probatórios (localizado, não verificado, ausência verificada) em que o terceiro só existe após os quatro gabaritos executados e registrados. E a vigência automática: um analisador de datas brasileiras imperfeitas (meses sem dia, listas de datas, formatos mistos) classifica cada decreto como ativo, vencido no prazo típico ou de vigência indeterminada, a cada atualização, sem fila de julgamento humano e sem jamais expirar um registro por conta própria.'),
  P('O banco resultante cobre as 27 unidades federativas, as 27 capitais e 254 registros municipais individuais. As categorias observadas na fotografia de 26/08/2026 aparecem na Figura 4: planos preventivos dominam (103), seguidos de decretos de resposta (98, registrados e excluídos da pontuação), planos em elaboração (18), registros não localizados (15), planos de ciclos anteriores (11), coberturas por instrumento estadual (5) e atos não relacionados ao ciclo (4).'),
  H2('3.4 Descoberta automatizada e leitura de conteúdo'),
  P('Duas esteiras automatizadas alimentam a verificação humana. A varredura de diários oficiais usa a API do Querido Diário (Open Knowledge Brasil), com consultas em lote por unidade federativa e um modo de descoberta nacional de termos que aprende o vocabulário real dos atos (emergência hídrica, estiagem prolongada, operação estiagem) antes de buscar por ele. E o leitor de conteúdo de decretos aplica três dicionários versionados ao texto integral de cada ato: um de desregulação (dispensas licitatórias, flexibilizações), um de proteção (abrigos, estoques, alertas) e um antecipatório, que após o refinamento da seção 4.2 inclui os termos de limiar observacional das três famílias de risco (monitor de secas, aviso vermelho, cota de alerta, risco de fogo). O desenho de governança é rígido: as esteiras geram pistas e marcações, nunca pontuação; a conversão de pista em registro exige a verificação documental humana da fase dois, e o único ponto de julgamento humano permanente do sistema é a avaliação das contribuições do formulário público, que passam por seis regras automáticas de triagem antes de chegar à editoria.'),
  ...FIG('/tmp/fig4_categorias.png', 'Figura 4. Registros municipais verificados por categoria (n = 254, corte de 26/08/2026). Decretos de resposta são registrados e excluídos da pontuação.', 560, 272),

  // ---- 4 metodologia ----
  H1('4. Metodologia do índice'),
  H2('4.1 Componentes e agregação'),
  P('O MARÉ de cada estado combina três componentes em escala 0 a 100: o instrumento estadual (existência e especificidade do plano para o ciclo, avaliada contra o risco projetado pelos boletins federais, com a correspondência risco-instrumento ancorada na COBRADE, a taxonomia oficial de desastres do S2iD); a população coberta (fração dos habitantes, pelo Censo 2022, vivendo em municípios com instrumento preventivo, com créditos decrescentes por categoria e o desconto de cinquenta por cento na camada declarada); e a antecipação (posição temporal do instrumento frente ao boletim de 29/06/2026). A agregação usa pesos iguais com elemento geométrico e piso:'),
  EQ('MARÉ = (1/3)·(C₁ + C₂ + C₃) · [max(G, piso)/100]^γ,  com G = (C₁·C₂·C₃)^(1/3)'),
  P('O piso resolve o problema clássico do zero na média geométrica e preserva a não-compensabilidade parcial: um estado sem instrumento estadual não alcança nota alta por cobertura municipal, e vice-versa. A incerteza é quantificada por Monte Carlo: dez mil sorteios perturbam os pesos e reportam, para cada estado, o intervalo de posições entre os percentis 5 e 95, publicado junto ao ranking.'),
  H2('4.2 O teste do objeto e o refinamento dos limiares'),
  P('A fronteira mais delicada é o ato antecipatório: decreto ou plano que dispara antes do dano. O teste do objeto aprova o ato que (i) cria estrutura, competência ou operação, (ii) dispara por gatilho de previsão ou por limiar em índice observacional oficial, e (iii) não declara dano consumado para acessar recurso. A segunda condição foi ampliada durante o desenvolvimento ao se examinar a estiagem, fenômeno de instalação lenta em que o análogo funcional da previsão é o índice observacional: o Monitor de Secas (ANA/Funceme) para o grupo Seca, os avisos por cor do Inmet, os alertas do Cemaden e as cotas fluviais de referência para a família das chuvas, o Risco de Fogo do INPE para a frente de incêndio. O paralelo internacional verificado é a designação fast-track do USDA, quase automática quando o condado atinge a categoria D2 do U.S. Drought Monitor por oito semanas consecutivas: declaração por limiar de mapa, não por avaliação de dano.'),
  H2('4.3 Reprodutibilidade'),
  P('Todo o cálculo é reprodutível a partir dos dados publicados. O trecho a seguir é extraído verbatim do motor (recalcular_mare.py), que qualquer auditor executa em modo de verificação para reproduzir os 270 campos do índice:'),
  ...CODE(trecho),
  P('Quatro portões automáticos precedem cada publicação: consistência de dados e figuras (todo mapa e gráfico do site é conferido contra o banco e a classificação canônica), recálculo independente do índice, verificação estrutural das páginas e simulação de navegação em navegador sintético. A suíte inclui testes negativos documentados: quebras propositais que os portões devem detectar.', { par: { spacing: { before: 120, after: 160 } } }),

  H2('4.4 Exclusões fundamentadas: a engenharia da rota do dano'),
  P('A exclusão dos atos de resposta (Correção B da série metodológica) tem fundamento duplo. O empírico está na seção 2.3. O normativo foi verificado em fonte primária: a Portaria MDR 260/2022, que rege o reconhecimento federal, ancora todo o fluxo em dano materializado, com formulário de informações do desastre, fotografias georreferenciadas dos danos e laudos; o teste desta metodologia, apelidado internamente de teste-fósforo, pergunta o que o ato acende: estrutura antes do dano, ou acesso a recurso depois dele. A cadeia federal, por construção, só acende a segunda. O corolário institucional, documentado na seção 6, é que não existe rota federal brasileira de reconhecimento por iminência; os decretos municipais que invocam risco iminente o fazem como cláusula de poderes operacionais, não como fundamento de reconhecimento. O caso de Porto Velho em 2024, decreto de emergência genuinamente antecipatório ante a seca anunciada do rio Madeira, é o precedente subnacional que o teste do objeto foi desenhado para acolher.'),
  H2('4.5 A correspondência risco-instrumento na COBRADE'),
  P('A avaliação de adequação entre o risco projetado e a área coberta pelo instrumento estadual usa a taxonomia oficial: o grupo climatológico Seca (COBRADE 1.4.1) compreende estiagem (1.4.1.1.0), seca (1.4.1.2.0, definida como o desequilíbrio hidrológico grave que fundamenta a segurança hídrica), incêndio florestal (1.4.1.3.1 e 1.4.1.3.2) e baixa umidade do ar (1.4.1.4.0); um instrumento que ataca qualquer membro do grupo cobre o risco projetado do grupo. Chuvas intensas (grupo Meteorológico, 1.3) e inundações (grupo Hidrológico, 1.2) formam a família causal das chuvas, independente do grupo Seca. O resultado da reavaliação dos 27 sob essa régua: dezesseis estados cobrem, um cobre parcialmente (Mato Grosso do Sul, instrumento de incêndio ante risco duplo), um diverge (Minas Gerais, instrumento de chuvas ante risco de seca), sete não têm instrumento e dois não têm sinal elevado projetado. Essa dimensão é publicada como camada contextual e mapa próprio; sua promoção a fator multiplicativo do índice, com escala ordinal e confiabilidade entre avaliadores, é o núcleo da versão 2.3.'),
  H2('4.6 Governança de versões e faixas'),
  P('Toda mudança tem estatuto declarado. A série 2.2 partiu da reestruturação populacional (fusão de capital e municípios num componente único ponderado pelo Censo 2022), passou pela correção das exclusões e chegou à v2.2.3, expansão metodológica sem alteração de motor, com os 270 campos do índice reproduzidos idênticos antes e depois de cada mudança. A regra de versão maior reserva alterações de pontuação a versões anunciadas com antecedência, precisamente para blindar o índice contra o oportunismo de ajustar critérios após observar resultados. As faixas interpretativas passaram por quatro nomenclaturas, todas preservadas em histórico auditável: a original (crítico a avançado) foi aposentada por embutir juízo de suficiência que o índice não mede; a segunda (estágios de desenvolvimento) por metáfora de processo; a terceira (ponto de partida a referência nacional), de convite à publicação, foi aposentada em 31/08/2026 por não passar no teste de compreensão imediata pelo cidadão; a vigente (estágio inicial, em construção, consolidado, avançado) reassume o vocabulário de estágio com o objeto explicitado — o estágio do arcabouço público publicado, não da capacidade — com os cortes numéricos intocados e a guarda de que a leitura probatória permanece regida pela definição do objeto.'),

  // ---- 5 resultados ----
  H1('5. Resultados da fotografia de 26/08/2026'),
  P('A média nacional é 41,1, na faixa denominada em construção. A Figura 1 apresenta os 27 estados; a Figura 2, a distribuição pelas quatro faixas, cuja nomenclatura de estágio (estágio inicial, em construção, consolidado, avançado) é decisão editorial documentada, escolhida pelo critério de compreensão imediata pelo cidadão, com os cortes numéricos e a leitura probatória preservados. O Paraná lidera, sustentado por instrumento estadual específico, levantamento nominal de planos municipais e antecipação; sete estados permanecem sem instrumento estadual localizado, condição registrada como ausência de localização após bateria de buscas, nunca como afirmação de inexistência.'),
  ...FIG('/tmp/fig1_estados.png', 'Figura 1. MARÉ v2.2.3 pelos 27 estados, ordenados; cores pelas faixas; linha tracejada na média nacional (41,1).', 500, 586),
  ...FIG('/tmp/fig2_faixas.png', 'Figura 2. Distribuição dos estados pelas quatro faixas do índice.', 540, 278),
  P('A Figura 3 resume a correspondência entre risco projetado e área coberta pelos instrumentos, na taxonomia COBRADE: dezesseis estados cobrem o risco projetado ou suas manifestações do mesmo grupo, um cobre parcialmente, um diverge, sete não têm instrumento e dois não têm sinal elevado projetado para o trimestre. A concentração no grupo Seca (quinze instrumentos nas suas duas frentes) espelha a geografia do risco projetado para Norte e Nordeste.'),
  ...FIG('/tmp/fig3_cobrade.png', 'Figura 3. Áreas temáticas dos instrumentos estaduais vigentes, classificadas pela COBRADE (instrumentos multiárea contam em cada frente).', 540, 262),

  H2('5.1 Leituras destacadas e erratas como método'),
  P('Três leituras ilustram o comportamento do índice. O Paraná lidera por acúmulo nas três dimensões: instrumento estadual específico, o único sistema declaratório integrado ao órgão de defesa civil (SISDC) e antecipação documentada. O Rio Grande do Sul combina instrumento, a maior operação de transferência preventiva localizada no país e a única lista nominal pública de repasses, ilustrando o efeito colateral virtuoso discutido na seção 6.2. E o Amapá demonstra a sensibilidade honesta do método: reclassificação de um único registro da capital, de não localizado para plano em elaboração após segunda bateria com gabarito ampliado, tirou o estado do zero, evidenciando que, em estados de arcabouço rarefeito, cada documento pesa, e que a bateria negativa é tão decisiva quanto a positiva. As erratas são tratadas como método, não como constrangimento: as correções de Belém (plano rebaixado a não localizado após falha de verificação de link) e de Porto Alegre (elevação após localização do documento) estão registradas com data e efeito, e a regra que as gerou (nenhum registro pontua sem link verificado) entrou nos portões automáticos.'),

  // ---- 6 discussão ----
  H1('6. Discussão'),
  H2('6.1 Preparação demonstrável como objeto'),
  P('A escolha de medir o arcabouço público, e não a capacidade instalada, não é uma limitação envergonhada: é a tese. O índice afirma, com valor probatório assimétrico declarado, que nota baixa é evidência forte de ausência de arcabouço, enquanto nota alta é condição necessária e não suficiente de preparo efetivo. Essa assimetria, rara em índices da área, protege o leitor do erro mais comum: confundir papel publicado com prontidão real.'),
  H2('6.2 Decisão, não riqueza'),
  P('Publicar um plano custa perto de zero; por isso a régua é justa entre estados pobres e ricos, e os dados confirmam que a posição no índice não acompanha o produto per capita. Essa propriedade orientou a decisão mais debatida do desenvolvimento: o financiamento preventivo, revelado pelo programa Prepara RS (Resolução 008/FUNDEC/2026, que transferiu 32,3 milhões de reais a 138 municípios antes de qualquer dano do ciclo, condicionados a plano de contingência atualizado), recebe reconhecimento editorial mas não pontua. Quatro razões, registradas em detalhe na metodologia: pontuar fluxo financeiro injetaria um gradiente de riqueza que destruiria a tese; o caso gaúcho é parcialmente anômalo, nascido à sombra dos desastres de 2023 e 2024, e pontuá-lo agora faria o dano passado entrar na nota presente por via indireta; um componente com um estado em cem e vinte e seis em zero é degenerescência estatística; e nota zero sem bateria negativa específica viola o protocolo probatório do próprio índice. A decisão em dois tempos, com a bateria construída nesta versão e a promoção do instrumento a subcritério prevista para a versão 3, é o compromisso público que resolve a tensão.'),
  H2('6.3 O limiar público como trade-off'),
  P('A comparação internacional convergiu para um achado: nos desenhos que tornam a precocidade possível (a rota peruana do peligro inminente, a emergência pré-desastre do Stafford Act, o gatilho D2 do USDA, as fases graduais quenianas, o financiamento antecipatório por contrato), a inovação comum é transferir o disparo da caneta discricionária para o limiar público. O registro é feito com o estatuto probatório declarado: a evidência verificada sustenta o efeito nos dois sentidos pela mesma fonte, a velocidade (o socorro da seca americana chegando no mesmo ano, contra os dois a três anos da era discricionária) e a patologia (o efeito-penhasco da linha do condado). O limiar é um trade-off documentável, não uma solução única; regras não se defendem sozinhas de revogação. O Brasil, que mantém Monitor de Secas, Risco de Fogo e cotas fluviais tecnicamente maduros e juridicamente inertes, tem nesse acoplamento o seu espaço de desenho mais evidente.'),
  H2('6.4 O que o processo ensinou ao método'),
  P('Três aprendizados de engenharia metodológica merecem registro acadêmico. A verificação em camadas (asserções antes de toda escrita, portões antes de todo selo, testes negativos para provar que os portões mordem) transferiu para o pipeline editorial práticas de engenharia de software, e cada incidente do desenvolvimento virou regra ou portão novo. O vocabulário probatório de três estados (localizado, não verificado, ausência verificada) impede a inflação silenciosa de ausências em zeros. E a disciplina de claims (a afirmação pública máxima é sempre a mais fraca sustentada pela verificação: não localizamos, nunca somos os únicos) mostrou-se aplicável à própria literatura, com o corpo empírico conhecido e ainda não verificado listado como fila, não como fundamento.'),

  H2('6.5 Dois trilhos: a anatomia completa do financiamento'),
  P('O caso Prepara RS merece a anatomia completa porque revela o desenho institucional inteiro. O trilho federal exige decreto, registro no S2iD, reconhecimento por portaria no Diário Oficial da União e só então libera recurso no Cartão de Pagamento de Defesa Civil: seis etapas ancoradas no dano. O trilho estadual gaúcho, pela Resolução 008/FUNDEC de 12/06/2026, transferiu recursos fundo a fundo antes de qualquer dano do ciclo, condicionados a plano de contingência atualizado e coordenador designado, com focalização pelo histórico (calamidade homologada em 2023 ou 2024, áreas de risco mapeadas pelo SGB, recorrência de inundações). A leitura precisa importa: o gatilho é ex-ante, a focalização é pelo dano passado; remunera-se o plano, mira-se quem provou exposição. A decisão de não pontuar nesta versão decompõe o objeto em três: o fluxo (os valores) não pontua nunca, pelo gradiente de riqueza; a execução pertence a um futuro painel de capacidade; o instrumento (a norma com condicionalidade) é o único candidato legítimo, e entra na versão 3 como subcritério, quando a bateria negativa de financiamento estiver completa nas 27 unidades e o próprio ciclo, provavelmente, tiver dissolvido a degenerescência do caso único. Nesta versão, o reconhecimento é editorial e visível: card do estado e relatório citam o instrumento, a norma e a cláusula de não pontuação.'),
  H2('6.6 Registro comparado: cinco desenhos para agir mais rápido'),
  P('Como elementos para o debate público, sem advocacy, o trabalho registra cinco desenhos institucionais observados em outros arranjos, pareados às lacunas brasileiras documentadas: a rota de reconhecimento por iminência ou limiar (o peligro inminente peruano ancorado nos informes do ENFEN; a emergência pré-desastre do Stafford Act americano); o acoplamento normativo entre índices oficiais e consequências automáticas (o gatilho D2 do USDA, ante um Brasil que mantém Monitor de Secas, Risco de Fogo e cotas fluviais tecnicamente maduros e juridicamente inertes); a transferência preventiva fundo a fundo em escala federal (o desenho que o Prepara RS provou viável por baixo, vedado na rota federal pela lógica de resposta das transferências sumárias); as fases graduadas pré-emergência com ações e recursos próprios (o desenho queniano e da classificação IPC); e os protocolos antecipatórios com financiamento pré-arranjado por contrato, em que o dinheiro espera o gatilho. A síntese, com o estatuto probatório da seção 6.3: em todos, a inovação é transferir o disparo da caneta discricionária para o limiar público, um trade-off documentável entre velocidade e as patologias próprias do limiar.'),
  H2('6.7 Convivendo com um monitor par'),
  P('O ciclo produziu ao menos dois esforços independentes de monitoramento, e a metodologia optou por tratar a relação com o monitor do Instituto Talanoa/Política por Inteiro pela engenharia das diferenças, não pela retórica da distinção: uma anatomia de divergência em cinco eixos (objeto, unidade de registro, fonte, vocabulário e regra de crédito), cada um com predições falseáveis registradas antes da conciliação fina. Uma predição já foi confirmada no desenvolvimento: a integração de seis decretos catarinenses localizados primeiro pelo catálogo par e verificados em fonte primária por este monitor, no exato fluxo que a anatomia previa (o par como sistema de descoberta, a verificação própria como sistema de prova). A conciliação registro a registro integra a fila pré-publicação.'),
  H2('6.8 Limitações'),
  P('Sete limitações permanecem declaradas. O índice não mede capacidade instalada, suficiência de recursos, qualidade técnica dos planos nem execução; mede arcabouço público. A camada declarada depende de três sistemas estaduais heterogêneos. A varredura de diários cobre o universo do Querido Diário, que não é o universo dos municípios. A avaliação risco-instrumento é categórica, ainda sem gradação de qualidade (objeto da versão 2.3). O piso da agregação é escolha normativa sem validação empírica externa, mitigada pela análise de sensibilidade. A unicidade do financiamento preventivo gaúcho é claim de não localização, não de inexistência. E parte do corpo empírico internacional citado na discussão permanece, por decisão de disciplina probatória, em fila de verificação, listado como tal.'),

  // ---- 7 considerações ----
  H1('7. Considerações finais'),
  P('O MARÉ demonstra que é possível medir, com fontes públicas e método reprodutível, quanto da preparação para um evento climático anunciado está demonstrado em documento público, e convertê-lo em incentivo: o índice sobe a cada plano preventivo publicado. A fotografia de agosto de 2026 mostra um país a caminho, com liderança clara, sete ausências e uma inovação subnacional (a transferência preventiva gaúcha) que aponta o desenho institucional faltante na esfera federal. A agenda declarada inclui, na versão 2.3, o fator de alinhamento risco-plano com confiabilidade entre avaliadores, e, na versão 3, a promoção do instrumento de financiamento preventivo a subcritério, condicionada à bateria negativa completa. O monitor permanece o que a metodologia o obriga a ser: um convite público, verificável e honesto à antecipação.'),
  new Paragraph({ children: [new PageBreak()] }),

  // ---- apêndices ----
  H1('Apêndice A. Créditos por categoria municipal'),
  P('A tabela consolida os créditos da camada municipal do componente de população coberta. A coluna de crédito declarado aplica o desconto de cinquenta por cento à cobertura declarada sem documento localizado.'),
  new Table({
    columnWidths: [3800, 2000, 2600],
    width: { size: 8400, type: WidthType.DXA },
    rows: [
      new TableRow({ children: ['Categoria do registro', 'Crédito documentado', 'Crédito declarado (50%)'].map(t =>
        new TableCell({ width: { size: t.length > 22 ? 2600 : t.length > 16 ? 2000 : 3800, type: WidthType.DXA }, shading: { type: ShadingType.CLEAR, fill: 'EFE8D8' },
          children: [new Paragraph({ children: [new TextRun({ text: t, bold: true, size: 20, font: 'Georgia', color: INK })] })] })) }),
      ...[['Plano preventivo específico do ciclo', '1,0', '0,5'],
          ['Plano em elaboração (evidência pública)', '0,7', '0,35'],
          ['Cobertura por instrumento estadual nominal', '0,4', 'não se aplica'],
          ['Plano de ciclo anterior sem atualização', 'crédito reduzido', 'não se aplica'],
          ['Decreto de resposta a dano', '0', '0'],
          ['Ato não relacionado ao ciclo', '0', '0'],
          ['Não localizado após bateria registrada', '0', '0']].map(linha =>
        new TableRow({ children: linha.map((t, i) =>
          new TableCell({ width: { size: [3800, 2000, 2600][i], type: WidthType.DXA },
            children: [new Paragraph({ children: [new TextRun({ text: t, size: 20, font: 'Georgia', color: INK })] })] })) })),
    ] }),
  P('', { par: { spacing: { after: 200 } } }),

  H1('Apêndice B. Reprodução e portões de qualidade'),
  P('Pipeline canônico de reprodução, executável por qualquer auditor sobre o pacote publicado: análise de vigência automática; recálculo integral do índice; portão um, de consistência de dados e figuras, que confere paridades entre os arquivos, o vocabulário de canais, as claims quantitativas do texto e, desde esta versão, todo mapa e gráfico do site contra o banco e a classificação canônica; portão dois, o recálculo independente que reproduz os 270 campos publicados; portão três, de estrutura das quatro páginas; portão quatro, de execução em navegador sintético, que renderiza mapas, gráficos e o fluxo de consulta municipal com os dados reais. A suíte inclui testes negativos documentados, quebras propositais que os portões devem acusar, sob o princípio de que um portão que nunca falhou não provou nada. Os artefatos publicados acompanham manifesto de integridade com o hash de cada arquivo.'),

  H1('Apêndice C. Estatuto probatório das afirmações'),
  P('Toda afirmação pública do monitor carrega um de três estatutos, e este documento os herda. Verificado em fonte primária nesta janela de desenvolvimento: a engenharia da Portaria MDR 260/2022 e do fluxo S2iD; a estrutura da COBRADE e seus códigos; a Resolução 008/FUNDEC e os critérios do Prepara RS; o gatilho D2 de oito semanas do U.S. Drought Monitor e o testemunho, na mesma fonte, da velocidade e do efeito-penhasco. Sustentado pela revisão de literatura encomendada, com referência completa: o corpo acadêmico da seção 2. Em fila de verificação, listado e não afirmado: a economia política das declarações presidenciais americanas, o socorro indiano sensível a eleições, as avaliações de transferências antecipatórias em Bangladesh, a criação e extinção do Fonden mexicano. A regra que governa os três estatutos é a mesma do banco de dados: a afirmação pública máxima é sempre a mais fraca que a verificação sustenta.'),
  new Paragraph({ children: [new PageBreak()] }),

  // ---- referências ----
  H1('Referências'),
  REF('BECCARI, B. A Comparative Analysis of Disaster Risk, Vulnerability and Resilience Composite Indicators. PLoS Currents Disasters, 2016.'),
  REF('BRASIL. Lei nº 12.340/2010 e Lei nº 12.608/2012 (Política Nacional de Proteção e Defesa Civil). Portaria MDR nº 260/2022. Classificação e Codificação Brasileira de Desastres (COBRADE).'),
  REF('CARDONA, O. D. Sistema de Indicadores para la Gestión del Riesgo de Desastres. Programa BID-IDEA, Universidad Nacional de Colombia, 2005.'),
  REF('CARREÑO, M. L.; CARDONA, O. D.; BARBAT, A. H. Urban seismic risk evaluation: a holistic approach. Natural Hazards, v. 40, p. 137-172, 2007.'),
  REF('CARTWRIGHT, N. Nature\u2019s Capacities and Their Measurement. Oxford University Press, 1989.'),
  REF('CHMUTINA, K. et al. What We Measure Matters: The Case of the Missing Development Data in Sendai Framework Monitoring. IJDRS, v. 12, n. 6, 2021.'),
  REF('GRECO, S.; ISHIZAKA, A.; TASIOU, M.; TORRISI, G. On the Methodological Framework of Composite Indices. Social Indicators Research, v. 141, 2019.'),
  REF('NARDO, M. et al. Handbook on Constructing Composite Indicators. OCDE/JRC, 2005/2008.'),
  REF('PINHEIRO, E. G. A efetividade do Planejamento Contingencial elaborado a partir das áreas de atenção. Tese (Doutorado em Gestão Urbana), PUCPR, 2016.'),
  REF('RIO GRANDE DO SUL. Resolução nº 008/FUNDEC, de 12/06/2026 (Programa Prepara RS). Defesa Civil Estadual.'),
  REF('SEDEC/MIDR. Indicador de Capacidade Municipal (ICM): metodologia. Portal gov.br/mdr, 2024. Plano Nacional de Proteção e Defesa Civil 2025-2035.'),
  REF('SILVA, A. H.; BATISTA, M. A politização dos desastres naturais: alinhamento partidário, declarações de emergência e a alocação de recursos federais para os municípios no Brasil. Opinião Pública, v. 26, n. 3, p. 522-555, 2020.'),
  REF('UNDRR. Sendai Framework Terminology on Disaster Risk Reduction, 2017; Global Assessment Report, 2019.'),
  REF('USDA/FSA. Secretarial disaster designations (fast track): gatilho D2 por 8 semanas consecutivas no U.S. Drought Monitor. Farm Service Agency, verificado em 27/08/2026.'),
  REF('VAN NIEKERK, D.; COETZEE, C.; NEMAKONDE, L. Implementing the Sendai Framework in Africa. IJDRS, v. 11, n. 2, 2020.'),
  P('Nota sobre fontes: as referências normativas e programáticas brasileiras (Portaria 260/2022, COBRADE, Resolução 008/FUNDEC) e o gatilho do USDA foram verificados em fonte primária durante o desenvolvimento; as referências acadêmicas provêm da revisão de literatura encomendada pelo Observatório, e o corpo empírico adicional citado na seção 6.3 permanece em fila de verificação, conforme o estatuto probatório declarado na metodologia.', { run: { size: 19, italics: true, color: MUT } }),
];

const doc = new Document({ sections: [{ properties: { page: { margin: { top: 1440, bottom: 1440, left: 1700, right: 1700 } } }, children: filhos }] });
Packer.toBuffer(doc).then(buf => { fs.writeFileSync('/mnt/user-data/outputs/TESE_Indice_MARE_El_Nino_Brasil.docx', buf); console.log('tese gravada:', buf.length, 'bytes'); });
